export const defaultUserData = {
  student_id: "",
  tu_id: "",
  member_id: "",
  member_ref: "",
  is_member: "",
  first_name: "",
  last_name: "",
  nick_name: "",
  first_name_eng: "",
  last_name_eng: "",
  first_name_old: "",
  last_name_old: "",
  sex: "",
  prefix: "",
  prefix_eng: "",
  picture: "",
  picture_name: "",
  picture_type: "",
  generation_id: "",
  m4_room_id: "",
  m5_room_id: "",
  m6_room_id: "",
  education_detail: "",
  email: "",
  email2: "",
  mobile: "",
  website: "",
  address1: "",
  address2: "",
  address_city_id: "",
  address_district_id: "",
  address_subdistrict_id: "",
  address_city: "",
  address_district: "",
  address_subdistrict: "",
  address_phone: "",
  address_postcode: "",
  address_country: "",
  job: "",
  position: "",
  office1: "",
  office2: "",
  office_city_id: "",
  office_district_id: "",
  office_subdistrict_id: "",
  office_city: "",
  office_district: "",
  office_subdistrict: "",
  office_phone: "",
  office_postcode: "",
  office_country: "",
  consent: "",
  consent_g1: "",
  consent_g2: "",
  consent_g3: "",
  consent_g4: "",
  consent_g5: "",
  consent_details: "",
  active: "",
  student_type: "",
  student_type_number: "",
  comment: "",
  create_time: "",
  create_by: "",
  update_time: "",
  update_by: "",
};

export enum LoadingStatus {
  "LOADING" = "LOADING",
  "IDLE" = "IDLE",
  "ERROR" = "ERROR",
  "FINISH" = "FINISH",
}
